## Numpy Array and Basic
Learn about numpy

In [1]:
import numpy as np

### Creating array from list

In [6]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr_2d=np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs numpy array

In [23]:
py_list=[1,2,3]
print("Python list multiplication ", py_list*2)

np_array=np.array([1,2,3])
print("Python array multiplication ", np_array*2)

import time

start =time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time: ", time.time()-start)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.09558653831481934

 Numpy operation time:  0.006966590881347656


### Creating array from scratch

In [21]:
zeros= np.zeros((3,4))
print("Zeros array: \n", zeros)

ones= np.ones((3,4))
print("One array: \n", ones)

full= np.full((3,3),6)
print("Full array: \n", full)

random= np.random.random((2,3))
print("Random array: \n", random)

sequence= np.arange(0,10,2)
print("Sequence array: \n", sequence)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random array: 
 [[0.0691486  0.77765508 0.79713995]
 [0.57116314 0.33103766 0.96764622]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [24]:
vector= np.array([1,2,3])
print("Vector: ", vector)

matrix= np.array([[1,2,3],[4,5,6]])
print("Matrix: ", matrix)

tensor= np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]] )
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [31]:
arr= np.array([[1,2,3],[4,5,8] ])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Data Type", arr.dtype)

Shape (4, 3)
Dimension 2
Size 12
Data Type int64


### Array Reshaping

In [48]:
arr= np.arange(12)
print("Original array: ", arr)

reshaped_array=arr.reshape((3,4))
print("\n Reshaped array: ", reshaped_array)

flattened= reshaped_array.flatten()
print("\n Flattened array: ", flattened)

# ravel (returns view, instead of copy)
raveled= flattened.ravel()
print("\n Raveled array: ", raveled)

# Transpose
transpose=reshaped_array.T
print("\n Transpose array: ", transpose)


Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
