### Numpy Array operation

In [4]:
import numpy as np

In [5]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negatice Indexing", arr[-3])


Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negatice Indexing 8


In [6]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire row", arr_2d[1])
print("Specific column", arr_2d[:,1])


Specific element 6
Entire row [4 5 6]
Specific column [2 5 8]


## Sorting

In [7]:
unsorted_arr=np.array([2,5,1,8,6,1,9,0])
print("Sorted array", np.sort(unsorted_arr))

arr_2d_unsorted= np.array([[3,2],
                           [9,1],
                           [4,0]])
print("Sorted 2D array by column",np.sort(arr_2d_unsorted,axis=0))   #axis=0 for column sorting
print("Sorted 2D array by row",np.sort(arr_2d_unsorted,axis=1))      #axis=1 for row sorting

Sorted array [0 1 1 2 5 6 8 9]
Sorted 2D array by column [[3 0]
 [4 1]
 [9 2]]
Sorted 2D array by row [[2 3]
 [1 9]
 [0 4]]


## Filter array

In [8]:
numbers= np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers % 2 == 0]
print("Even numbers", even_numbers)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [9]:
masks= numbers>5
print("Numbers greater than 5: ", numbers[masks])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [10]:
indices=[1,3,5]
print(numbers[indices])

where_result= np.where(numbers>5)
print("NP where", numbers[where_result])

[2 4 6]
NP where [ 6  7  8  9 10]


In [11]:
condition_array=np.where(numbers>5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing data

In [17]:
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])

combined_array= np.concatenate((arr_1,arr_2))
print("Combinated array: ",combined_array)

Combinated array:  [1 2 3 4 5 6]


### Array Compatibilty

In [20]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])

print("Compatibility shape:",arr1.shape == arr2.shape)

Compatibility shape: True


In [24]:
original_arr=np.array([[1,2],[3,4]])
new_row=np.array([5,6])

with_new_row=np.vstack((original_arr,new_row))    # vstack generally add new "row"    vertical stack(vstack)
# print(original_arr)
# print(with_new_row)

with_cols=np.array([[7],[8]])
with_new_cols=np.hstack((original_arr,with_cols))   # hstack generally add new "column"    horizintal stack(hstack)
print(original_arr)
print(with_new_cols)

[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [27]:
arr=np.array([1,2,3,4,5,6,7])
deleted=np.delete(arr,2)
print(deleted)

[1 2 4 5 6 7]
[1 2 3 4 5 6 7]
